# Makefile
#----------------------------------------------------------------------------------------
#
#  Project: ParserGen 1.01
#
#  License: Boost Software License - Version 1.0 - August 17th, 2003 
#
#            see http://www.boost.org/LICENSE_1_0.txt or the local copy
#
#  Copyright (c) 2012 Sergey Strukov. All rights reserved.
#
#----------------------------------------------------------------------------------------

CCORE_ROOT = ../..

include $(CCORE_ROOT)/Makefile.host

OBJ_PATH = obj

TARGET = $(HOME)/bin/ParserGen.exe

include $(CCORE_ROOT)/Target/Makefile.app

run: $(TARGET) 
	$(TARGET) ../LangLR1-tools/AMP/State.ddl ../LangLR1-tools/AMP/gen/Prefix





