/* Parser.gen.cpp */ 

#include "Parser.gen.h"

/* lang AMP */ 

namespace AMP {

/* types */ 

const char * GetTextDesc(RIndex i)
 {
  static const char *const Table[]=
   {
    "<-",
    "A1",
    "A2",
    "M1",
    "M2",
    "P1",
    "P2",
    "..."
   };

  return Table[i];
 }

const char * GetTextDesc(TIndex i)
 {
  static const char *const Table[]=
   {
    "(End)",
    "T(\"(\")",
    "T(\")\")",
    "T(\"*\")",
    "T(\"+\")",
    "T(\"x\")",
    "..."
   };

  return Table[i];
 }

const char * GetTextDesc(NTIndex i)
 {
  static const char *const Table[]=
   {
    "(End)",
    "T(\"(\")",
    "T(\")\")",
    "T(\"*\")",
    "T(\"+\")",
    "T(\"x\")",
    "A",
    "M",
    "P",
    "..."
   };

  return Table[i];
 }

/* struct RuleProp */ 

const RuleProp RuleProp::Table[RIndexLim-1]=
 {
  {RIndex(1),RuleLength(1),NTIndex(6),{NTIndex(7),}},
  {RIndex(2),RuleLength(3),NTIndex(6),{NTIndex(6),NTIndex(4),NTIndex(7),}},
  {RIndex(3),RuleLength(1),NTIndex(7),{NTIndex(8),}},
  {RIndex(4),RuleLength(3),NTIndex(7),{NTIndex(8),NTIndex(3),NTIndex(7),}},
  {RIndex(5),RuleLength(1),NTIndex(8),{NTIndex(5),}},
  {RIndex(6),RuleLength(3),NTIndex(8),{NTIndex(1),NTIndex(6),NTIndex(2),}},
 };

const RuleProp RuleProp::ShiftTable[TIndexLim]=
 {
  {RIndexShift,RuleLengthZero,NTIndex(0)},
  {RIndexShift,RuleLengthZero,NTIndex(1)},
  {RIndexShift,RuleLengthZero,NTIndex(2)},
  {RIndexShift,RuleLengthZero,NTIndex(3)},
  {RIndexShift,RuleLengthZero,NTIndex(4)},
  {RIndexShift,RuleLengthZero,NTIndex(5)},
 };

/* struct State */ 

const State State::Table[StateIndexLim]=
 {
  {
   {
    RIndex(0),
    RIndex(1),
    RIndex(0),
    RIndex(0),
    RIndex(0),
    RIndex(1),
   },
   {
    StateIndex(0),
    StateIndex(2),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(3),
    StateIndex(4),
    StateIndex(5),
    StateIndex(17),
   }
  },
  {
   {
    RIndex(0),
    RIndex(1),
    RIndex(0),
    RIndex(0),
    RIndex(0),
    RIndex(1),
   },
   {
    StateIndex(0),
    StateIndex(6),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(7),
    StateIndex(8),
    StateIndex(9),
    StateIndex(20),
   }
  },
  {
   {
    RIndex(6),
    RIndex(0),
    RIndex(0),
    RIndex(6),
    RIndex(6),
    RIndex(0),
   },
   {
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
   }
  },
  {
   {
    RIndex(1),
    RIndex(0),
    RIndex(0),
    RIndex(0),
    RIndex(1),
    RIndex(0),
   },
   {
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(10),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
   }
  },
  {
   {
    RIndex(2),
    RIndex(0),
    RIndex(0),
    RIndex(0),
    RIndex(2),
    RIndex(0),
   },
   {
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
   }
  },
  {
   {
    RIndex(0),
    RIndex(1),
    RIndex(0),
    RIndex(0),
    RIndex(0),
    RIndex(1),
   },
   {
    StateIndex(0),
    StateIndex(6),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(7),
    StateIndex(11),
    StateIndex(9),
    StateIndex(20),
   }
  },
  {
   {
    RIndex(0),
    RIndex(0),
    RIndex(6),
    RIndex(6),
    RIndex(6),
    RIndex(0),
   },
   {
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
   }
  },
  {
   {
    RIndex(0),
    RIndex(0),
    RIndex(1),
    RIndex(0),
    RIndex(1),
    RIndex(0),
   },
   {
    StateIndex(0),
    StateIndex(0),
    StateIndex(12),
    StateIndex(0),
    StateIndex(13),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
   }
  },
  {
   {
    RIndex(0),
    RIndex(0),
    RIndex(2),
    RIndex(0),
    RIndex(2),
    RIndex(0),
   },
   {
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
   }
  },
  {
   {
    RIndex(0),
    RIndex(1),
    RIndex(0),
    RIndex(0),
    RIndex(0),
    RIndex(1),
   },
   {
    StateIndex(0),
    StateIndex(2),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(3),
    StateIndex(0),
    StateIndex(15),
    StateIndex(17),
   }
  },
  {
   {
    RIndex(0),
    RIndex(0),
    RIndex(1),
    RIndex(0),
    RIndex(1),
    RIndex(0),
   },
   {
    StateIndex(0),
    StateIndex(0),
    StateIndex(18),
    StateIndex(0),
    StateIndex(13),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
   }
  },
  {
   {
    RIndex(7),
    RIndex(0),
    RIndex(0),
    RIndex(7),
    RIndex(7),
    RIndex(0),
   },
   {
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
   }
  },
  {
   {
    RIndex(0),
    RIndex(1),
    RIndex(0),
    RIndex(0),
    RIndex(0),
    RIndex(1),
   },
   {
    StateIndex(0),
    StateIndex(6),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(7),
    StateIndex(0),
    StateIndex(19),
    StateIndex(20),
   }
  },
  {
   {
    RIndex(0),
    RIndex(1),
    RIndex(0),
    RIndex(0),
    RIndex(0),
    RIndex(1),
   },
   {
    StateIndex(0),
    StateIndex(6),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(7),
    StateIndex(0),
    StateIndex(21),
    StateIndex(20),
   }
  },
  {
   {
    RIndex(3),
    RIndex(0),
    RIndex(0),
    RIndex(0),
    RIndex(3),
    RIndex(0),
   },
   {
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
   }
  },
  {
   {
    RIndex(5),
    RIndex(0),
    RIndex(0),
    RIndex(0),
    RIndex(5),
    RIndex(0),
   },
   {
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
   }
  },
  {
   {
    RIndex(4),
    RIndex(0),
    RIndex(0),
    RIndex(1),
    RIndex(4),
    RIndex(0),
   },
   {
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(22),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
   }
  },
  {
   {
    RIndex(0),
    RIndex(0),
    RIndex(7),
    RIndex(7),
    RIndex(7),
    RIndex(0),
   },
   {
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
   }
  },
  {
   {
    RIndex(0),
    RIndex(0),
    RIndex(3),
    RIndex(0),
    RIndex(3),
    RIndex(0),
   },
   {
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
   }
  },
  {
   {
    RIndex(0),
    RIndex(0),
    RIndex(4),
    RIndex(1),
    RIndex(4),
    RIndex(0),
   },
   {
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(14),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
   }
  },
  {
   {
    RIndex(0),
    RIndex(0),
    RIndex(5),
    RIndex(0),
    RIndex(5),
    RIndex(0),
   },
   {
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
   }
  },
  {
   {
    RIndex(0),
    RIndex(1),
    RIndex(0),
    RIndex(0),
    RIndex(0),
    RIndex(1),
   },
   {
    StateIndex(0),
    StateIndex(2),
    StateIndex(0),
    StateIndex(0),
    StateIndex(0),
    StateIndex(3),
    StateIndex(0),
    StateIndex(16),
    StateIndex(17),
   }
  },
 };

} // namespace AMP

