# Makefile
#----------------------------------------------------------------------------------------
#
#  Project: LangLR1 1.00
#
#  License: Boost Software License - Version 1.0 - August 17th, 2003 
#
#            see http://www.boost.org/LICENSE_1_0.txt or the local copy
#
#  Copyright (c) 2011 Sergey Strukov. All rights reserved.
#
#----------------------------------------------------------------------------------------

CCORE_ROOT = ../..

CCORE_TARGET = WIN32

OBJ_PATH = obj

TARGET = $(HOME)/bin/LangLR1.exe

include $(CCORE_ROOT)/Target/Makefile.app

run: $(TARGET)
	cd ../LangLR1-tools/AMP && $(TARGET) AMP AMP.lang ../../$(CCORE_ROOT)





